# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy

on:
  # push:
  #   branches: ["main"]
  
  pull_request:
    branches: [ "main" ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

            # Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu/<PROJECT_DIRECTORY> &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main &&
            sudo npm ci &&
            sudo npm run build &&
            sudo pm2 stop ./dist/index.js &&
            sudo pm2 start ./dist/index.js
            '
      - run: npm run build --if-present
      - run: npm test
      - run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" .env
